name: Gnomock
description: Start Gnomock container available on port 23042
branding:
  icon: activity
  color: green
runs:
  using: composite
  steps:
    - run: |
        docker run --rm -d \
            -p 23042:23042 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $PWD:$PWD \
            orlangure/gnomock
        while ! nc -z localhost 23042; do
          sleep 0.2
        done
      shell: bash
