name: Gnomock
description: Start Gnomock container available on port 23042
branding:
  icon: activity
  color: green
runs:
  using: composite
  steps:
    - run: docker run --name gnomock -d -p 23042:23042 orlangure/gnomock
      shell: bash
